### ISSUE TITLE
Download error in fortnite

### ISSUE THREAD

**Issue by Kirbdabirb1** [Crunnie/Fortnite-iOS-Archive#5]
So I wanted to download the fortnite chapter 2 season two ipa and it was working out in the first half then it says this and I don’t know if there’s anyway to fix it
![D0CEDFD7-8D0A-4BAA-91C9-CC1C3023DCFB](https://user-images.githubusercontent.com/126831544/222582067-e5faf0c1-00a9-4734-8af0-5fece06ae212.png)

**Comment by Crunnie** [comment]
Sorry, I have no idea.
